import pandas as pd

def add_rolling_features(df: pd.DataFrame, window_size: int = 5) -> pd.DataFrame:
    """Adds rolling mean and std features for sensor data."""
    # Assuming the data is time-ordered. If it's effectively i.i.d., rolling might not make sense 
    # without a specific sequence context, but following requirements.
    # We'll apply this to numeric sensor columns.
    
    sensor_cols = ['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]']
    
    df_feat = df.copy()
    
    for col in sensor_cols:
        # Rolling Mean
        df_feat[f'{col}_rolling_mean'] = df_feat[col].rolling(window=window_size).mean()
        # Rolling Std
        df_feat[f'{col}_rolling_std'] = df_feat[col].rolling(window=window_size).std()
        # Delta (Change from previous)
        df_feat[f'{col}_delta'] = df_feat[col].diff()
        
    # Fill NAs generated by rolling/diff (usually first few rows)
    df_feat = df_feat.fillna(0)
    
    return df_feat
